package com.tailorcards.api;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;

import java.util.ArrayList;
import java.util.List;

/**
 * Baselined-production simulation using the pre-trade-assistant schema as Hibernate
 * (ddl-auto=update) generated it from the entities at commit 627bb11.
 */
@EnabledIf("isDockerAvailable")
class PostgreSqlFlywayBaselineLegacyEntitiesIntegrationTest extends AbstractFlywayBaselineIntegrationTest {

    // No cost_basis/pokemontcg_id on products and none of the trade tables
    private static final List<String> LEGACY_HIBERNATE_SCHEMA = List.of(
            """
            create table categories (
                id bigint generated by default as identity,
                description varchar(255),
                name varchar(255) not null unique,
                primary key (id)
            )""",
            """
            create table products (
                id bigint generated by default as identity,
                card_number varchar(255),
                card_set varchar(255),
                condition varchar(255),
                description varchar(1000),
                grading varchar(255),
                image_url varchar(255),
                name varchar(255) not null,
                price numeric(10,2) not null,
                status varchar(255),
                stock integer not null,
                version bigint default 0,
                category_id bigint not null,
                primary key (id)
            )""",
            """
            create table cart_items (
                id bigint generated by default as identity,
                cart_session_id varchar(255) not null,
                quantity integer not null,
                product_id bigint not null,
                primary key (id)
            )""",
            """
            create table orders (
                id bigint generated by default as identity,
                amount_total numeric(10,2),
                cart_session_id varchar(255),
                created_at timestamp(6) not null,
                currency varchar(10),
                customer_email varchar(255),
                customer_name varchar(255),
                product_ids varchar(1000),
                status varchar(255) not null,
                stripe_session_id varchar(255) not null unique,
                primary key (id)
            )""",
            """
            create table buylist_submissions (
                id bigint generated by default as identity,
                additional_comments TEXT,
                asking_price numeric(10,2),
                card_name varchar(255) not null,
                card_set varchar(255),
                created_at timestamp(6) with time zone not null,
                customer_email varchar(255) not null,
                customer_name varchar(255),
                status varchar(255) not null,
                tracking_token varchar(255) not null unique,
                primary key (id)
            )""",
            """
            create table buylist_submission_images (
                submission_id bigint not null,
                image_url varchar(255)
            )""",
            """
            create table submission_messages (
                id bigint generated by default as identity,
                created_at timestamp(6) with time zone not null,
                message TEXT not null,
                sender_email varchar(255) not null,
                sender_role varchar(255) not null,
                submission_id bigint not null,
                primary key (id)
            )""",
            "alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories",
            "alter table if exists cart_items add constraint FK1re40cjegsfvw58xrkdp6bac6 foreign key (product_id) references products",
            "alter table if exists buylist_submission_images add constraint FKbuylistimgsubmission foreign key (submission_id) references buylist_submissions",
            "alter table if exists submission_messages add constraint FKsubmsgsubmission foreign key (submission_id) references buylist_submissions"
    );

    static PostgreSQLContainer<?> postgres;

    static {
        if (isDockerAvailable()) {
            postgres = newPostgresContainer();
            postgres.start();
            List<String> statements = new ArrayList<>(LEGACY_HIBERNATE_SCHEMA);
            statements.addAll(LEGACY_DATA);
            executeStatements(postgres, statements);
        }
    }

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registerBaselinedPostgres(registry, postgres);
    }

    @Test
    @DisplayName("Legacy Hibernate-generated schema: V1 baselined, V2 creates trade tables and seeds, validate passes")
    void migratesBaselinedLegacyEntitySchema() {
        assertBaselinedSchemaMigrated();
    }
}
