--
-- PostgreSQL database dump
--

\restrict H4cAujG7YSb0wfemhRvBVNax7b6gidMC82Lxz2U3V0HtGfCxGsv0W7QD9vkxwTE

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.11 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: rls_auto_enable(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.rls_auto_enable() RETURNS event_trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: buy_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buy_rules (
    id bigint NOT NULL,
    priority integer NOT NULL,
    category_code character varying(100) NOT NULL,
    display_name character varying(200) NOT NULL,
    rate numeric(6,4) NOT NULL,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: buy_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.buy_rules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buy_rules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buylist_submission_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buylist_submission_images (
    submission_id bigint NOT NULL,
    image_url character varying(255)
);


--
-- Name: buylist_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buylist_submissions (
    id bigint NOT NULL,
    additional_comments text,
    asking_price numeric(10,2),
    card_name character varying(255) NOT NULL,
    card_set character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    customer_email character varying(255) NOT NULL,
    customer_name character varying(255),
    status character varying(255) NOT NULL,
    tracking_token character varying(255) NOT NULL
);


--
-- Name: buylist_submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.buylist_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buylist_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: card_liquidity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.card_liquidity (
    id bigint NOT NULL,
    pokemontcg_id character varying(100) NOT NULL,
    liquidity_tier character varying(50) NOT NULL,
    haircut numeric(6,4) NOT NULL,
    notes character varying(500)
);


--
-- Name: card_liquidity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.card_liquidity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_liquidity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    cart_session_id character varying(255) NOT NULL,
    quantity integer NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: manual_price_overrides; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.manual_price_overrides (
    id bigint NOT NULL,
    card_id character varying(100) NOT NULL,
    condition_or_grade character varying(50) NOT NULL,
    override_price_cad numeric(10,2) NOT NULL,
    notes character varying(500),
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: manual_price_overrides_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.manual_price_overrides ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.manual_price_overrides_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    amount_total numeric(10,2),
    cart_session_id character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(10),
    customer_email character varying(255),
    customer_name character varying(255),
    product_ids character varying(1000),
    status character varying(255) NOT NULL,
    stripe_session_id character varying(255) NOT NULL
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: price_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.price_snapshots (
    id bigint NOT NULL,
    card_id character varying(100) NOT NULL,
    price_usd numeric(10,2),
    price_cad numeric(10,2),
    source character varying(50),
    fetched_at timestamp with time zone NOT NULL
);


--
-- Name: price_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.price_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    description character varying(1000),
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    category_id bigint NOT NULL,
    card_number character varying(255),
    condition character varying(255),
    grading character varying(255),
    card_set character varying(255),
    status character varying(255),
    images text[],
    version bigint DEFAULT 0 NOT NULL,
    cost_basis numeric(10,2),
    pokemontcg_id character varying(255)
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submission_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.submission_messages (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    message text NOT NULL,
    sender_email character varying(255) NOT NULL,
    sender_role character varying(255) NOT NULL,
    submission_id bigint NOT NULL
);


--
-- Name: submission_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.submission_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submission_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trade_assistant_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trade_assistant_requests (
    id bigint NOT NULL,
    reference_code character varying(64) NOT NULL,
    flow_type character varying(20) NOT NULL,
    status character varying(30) NOT NULL,
    customer_name character varying(150) NOT NULL,
    customer_email character varying(150) NOT NULL,
    customer_phone character varying(50),
    decision character varying(30) NOT NULL,
    offered_amount numeric(10,2),
    counter_top_up numeric(10,2),
    customer_total_market_cad numeric(10,2),
    store_total_list_price_cad numeric(10,2),
    customer_cards_json text,
    store_products_json text,
    rule_trace_json text,
    explanation text,
    customer_notes text,
    admin_notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: trade_assistant_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trade_assistant_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trade_assistant_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trade_parameters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trade_parameters (
    id bigint NOT NULL,
    param_key character varying(100) NOT NULL,
    param_value numeric(12,4) NOT NULL,
    description character varying(500)
);


--
-- Name: trade_parameters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trade_parameters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trade_parameters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buy_rules buy_rules_category_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buy_rules
    ADD CONSTRAINT buy_rules_category_code_key UNIQUE (category_code);


--
-- Name: buy_rules buy_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buy_rules
    ADD CONSTRAINT buy_rules_pkey PRIMARY KEY (id);


--
-- Name: buylist_submissions buylist_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buylist_submissions
    ADD CONSTRAINT buylist_submissions_pkey PRIMARY KEY (id);


--
-- Name: card_liquidity card_liquidity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_liquidity
    ADD CONSTRAINT card_liquidity_pkey PRIMARY KEY (id);


--
-- Name: card_liquidity card_liquidity_pokemontcg_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.card_liquidity
    ADD CONSTRAINT card_liquidity_pokemontcg_id_key UNIQUE (pokemontcg_id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: manual_price_overrides manual_price_overrides_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_price_overrides
    ADD CONSTRAINT manual_price_overrides_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: price_snapshots price_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.price_snapshots
    ADD CONSTRAINT price_snapshots_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: submission_messages submission_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submission_messages
    ADD CONSTRAINT submission_messages_pkey PRIMARY KEY (id);


--
-- Name: trade_assistant_requests trade_assistant_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_assistant_requests
    ADD CONSTRAINT trade_assistant_requests_pkey PRIMARY KEY (id);


--
-- Name: trade_assistant_requests trade_assistant_requests_reference_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_assistant_requests
    ADD CONSTRAINT trade_assistant_requests_reference_code_key UNIQUE (reference_code);


--
-- Name: trade_parameters trade_parameters_param_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_parameters
    ADD CONSTRAINT trade_parameters_param_key_key UNIQUE (param_key);


--
-- Name: trade_parameters trade_parameters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trade_parameters
    ADD CONSTRAINT trade_parameters_pkey PRIMARY KEY (id);


--
-- Name: manual_price_overrides uk_override_card_condition; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_price_overrides
    ADD CONSTRAINT uk_override_card_condition UNIQUE (card_id, condition_or_grade);


--
-- Name: orders ukgkeltls6kwwpk41f577et02dj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT ukgkeltls6kwwpk41f577et02dj UNIQUE (stripe_session_id);


--
-- Name: buylist_submissions ukp9ie6jc8tqsneilsfhyosfnmt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buylist_submissions
    ADD CONSTRAINT ukp9ie6jc8tqsneilsfhyosfnmt UNIQUE (tracking_token);


--
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_price_override_card_condition; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_price_override_card_condition ON public.manual_price_overrides USING btree (card_id, condition_or_grade);


--
-- Name: idx_price_snapshot_card_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_price_snapshot_card_id ON public.price_snapshots USING btree (card_id);


--
-- Name: idx_price_snapshot_fetched_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_price_snapshot_fetched_at ON public.price_snapshots USING btree (fetched_at);


--
-- Name: idx_trade_req_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_req_created_at ON public.trade_assistant_requests USING btree (created_at);


--
-- Name: idx_trade_req_reference; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_req_reference ON public.trade_assistant_requests USING btree (reference_code);


--
-- Name: idx_trade_req_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trade_req_status ON public.trade_assistant_requests USING btree (status);


--
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: buylist_submission_images fk7iy29dpcrtvghjrne0wlpx8od; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buylist_submission_images
    ADD CONSTRAINT fk7iy29dpcrtvghjrne0wlpx8od FOREIGN KEY (submission_id) REFERENCES public.buylist_submissions(id);


--
-- Name: submission_messages fkbkmedlvpr6d54n3qvwpm7180j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submission_messages
    ADD CONSTRAINT fkbkmedlvpr6d54n3qvwpm7180j FOREIGN KEY (submission_id) REFERENCES public.buylist_submissions(id);


--
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: buy_rules; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.buy_rules ENABLE ROW LEVEL SECURITY;

--
-- Name: buylist_submission_images; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.buylist_submission_images ENABLE ROW LEVEL SECURITY;

--
-- Name: buylist_submissions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.buylist_submissions ENABLE ROW LEVEL SECURITY;

--
-- Name: card_liquidity; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.card_liquidity ENABLE ROW LEVEL SECURITY;

--
-- Name: cart_items; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

--
-- Name: categories; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

--
-- Name: flyway_schema_history; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.flyway_schema_history ENABLE ROW LEVEL SECURITY;

--
-- Name: manual_price_overrides; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.manual_price_overrides ENABLE ROW LEVEL SECURITY;

--
-- Name: orders; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

--
-- Name: price_snapshots; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.price_snapshots ENABLE ROW LEVEL SECURITY;

--
-- Name: products; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

--
-- Name: submission_messages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.submission_messages ENABLE ROW LEVEL SECURITY;

--
-- Name: trade_assistant_requests; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.trade_assistant_requests ENABLE ROW LEVEL SECURITY;

--
-- Name: trade_parameters; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.trade_parameters ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict H4cAujG7YSb0wfemhRvBVNax7b6gidMC82Lxz2U3V0HtGfCxGsv0W7QD9vkxwTE

