-- V1__initial_schema.sql
-- Baseline schema definition for Tailor Cards

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    price NUMERIC(10, 2) NOT NULL,
    image_url VARCHAR(255),
    stock INTEGER NOT NULL,
    category_id BIGINT NOT NULL,
    card_number VARCHAR(255),
    card_set VARCHAR(255),
    condition VARCHAR(255),
    grading VARCHAR(255),
    cost_basis NUMERIC(10, 2),
    pokemontcg_id VARCHAR(255),
    status VARCHAR(255) DEFAULT 'AVAILABLE',
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stripe_session_id VARCHAR(255) NOT NULL UNIQUE,
    customer_email VARCHAR(255),
    customer_name VARCHAR(255),
    amount_total NUMERIC(10, 2),
    currency VARCHAR(10),
    status VARCHAR(255) NOT NULL,
    cart_session_id VARCHAR(255),
    product_ids VARCHAR(1000),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_session_id VARCHAR(255) NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE buylist_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_token VARCHAR(255) NOT NULL UNIQUE,
    customer_email VARCHAR(255) NOT NULL,
    customer_name VARCHAR(255),
    card_name VARCHAR(255) NOT NULL,
    card_set VARCHAR(255),
    asking_price NUMERIC(10, 2),
    additional_comments TEXT,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE buylist_submission_images (
    submission_id BIGINT NOT NULL,
    image_url VARCHAR(255),
    CONSTRAINT fk_buylist_submission_images_submission FOREIGN KEY (submission_id) REFERENCES buylist_submissions (id)
);

CREATE TABLE submission_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    sender_role VARCHAR(255) NOT NULL,
    sender_email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_submission_messages_submission FOREIGN KEY (submission_id) REFERENCES buylist_submissions (id)
);

CREATE TABLE buy_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority INTEGER NOT NULL,
    category_code VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(200) NOT NULL,
    rate NUMERIC(6, 4) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE trade_parameters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    param_key VARCHAR(100) NOT NULL UNIQUE,
    param_value NUMERIC(12, 4) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE card_liquidity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemontcg_id VARCHAR(100) NOT NULL UNIQUE,
    liquidity_tier VARCHAR(50) NOT NULL,
    haircut NUMERIC(6, 4) NOT NULL,
    notes VARCHAR(500)
);

CREATE TABLE manual_price_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id VARCHAR(100) NOT NULL,
    condition_or_grade VARCHAR(50) NOT NULL,
    override_price_cad NUMERIC(10, 2) NOT NULL,
    notes VARCHAR(500),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_override_card_condition UNIQUE (card_id, condition_or_grade)
);
CREATE INDEX idx_price_override_card_condition ON manual_price_overrides (card_id, condition_or_grade);

CREATE TABLE price_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id VARCHAR(100) NOT NULL,
    price_usd NUMERIC(10, 2),
    price_cad NUMERIC(10, 2),
    source VARCHAR(50),
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_price_snapshot_card_id ON price_snapshots (card_id);
CREATE INDEX idx_price_snapshot_fetched_at ON price_snapshots (fetched_at);

CREATE TABLE trade_assistant_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_code VARCHAR(64) NOT NULL UNIQUE,
    flow_type VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_email VARCHAR(150) NOT NULL,
    customer_phone VARCHAR(50),
    decision VARCHAR(30) NOT NULL,
    offered_amount NUMERIC(10, 2),
    counter_top_up NUMERIC(10, 2),
    customer_total_market_cad NUMERIC(10, 2),
    store_total_list_price_cad NUMERIC(10, 2),
    customer_cards_json TEXT,
    store_products_json TEXT,
    rule_trace_json TEXT,
    explanation TEXT,
    customer_notes TEXT,
    admin_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_trade_req_reference ON trade_assistant_requests (reference_code);
CREATE INDEX idx_trade_req_status ON trade_assistant_requests (status);
CREATE INDEX idx_trade_req_created_at ON trade_assistant_requests (created_at);
