-- V2__seed_data.sql
-- Initial seed data for categories, buy rules, trade parameters, liquidity, and manual overrides
--
-- Production databases that predate Flyway are baselined at version 1, so V1 never runs there.
-- This script therefore first creates (idempotently) every trade-assistant table and products
-- column that V1 defines, so it works both after V1 on an empty database and on a baselined one.
-- Definitions must stay identical to V1__initial_schema.sql.

-- Products: columns added for the trade assistant
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_basis NUMERIC(10, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS pokemontcg_id VARCHAR(255);

CREATE TABLE IF NOT EXISTS buy_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority INTEGER NOT NULL,
    category_code VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(200) NOT NULL,
    rate NUMERIC(6, 4) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS trade_parameters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    param_key VARCHAR(100) NOT NULL UNIQUE,
    param_value NUMERIC(12, 4) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS card_liquidity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemontcg_id VARCHAR(100) NOT NULL UNIQUE,
    liquidity_tier VARCHAR(50) NOT NULL,
    haircut NUMERIC(6, 4) NOT NULL,
    notes VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS manual_price_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id VARCHAR(100) NOT NULL,
    condition_or_grade VARCHAR(50) NOT NULL,
    override_price_cad NUMERIC(10, 2) NOT NULL,
    notes VARCHAR(500),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_override_card_condition UNIQUE (card_id, condition_or_grade)
);
CREATE INDEX IF NOT EXISTS idx_price_override_card_condition ON manual_price_overrides (card_id, condition_or_grade);

CREATE TABLE IF NOT EXISTS price_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id VARCHAR(100) NOT NULL,
    price_usd NUMERIC(10, 2),
    price_cad NUMERIC(10, 2),
    source VARCHAR(50),
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_price_snapshot_card_id ON price_snapshots (card_id);
CREATE INDEX IF NOT EXISTS idx_price_snapshot_fetched_at ON price_snapshots (fetched_at);

CREATE TABLE IF NOT EXISTS trade_assistant_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_code VARCHAR(64) NOT NULL UNIQUE,
    flow_type VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_email VARCHAR(150) NOT NULL,
    customer_phone VARCHAR(50),
    decision VARCHAR(30) NOT NULL,
    offered_amount NUMERIC(10, 2),
    counter_top_up NUMERIC(10, 2),
    customer_total_market_cad NUMERIC(10, 2),
    store_total_list_price_cad NUMERIC(10, 2),
    customer_cards_json TEXT,
    store_products_json TEXT,
    rule_trace_json TEXT,
    explanation TEXT,
    customer_notes TEXT,
    admin_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_trade_req_reference ON trade_assistant_requests (reference_code);
CREATE INDEX IF NOT EXISTS idx_trade_req_status ON trade_assistant_requests (status);
CREATE INDEX IF NOT EXISTS idx_trade_req_created_at ON trade_assistant_requests (created_at);

-- Categories
INSERT INTO categories (id, name, description)
VALUES (1, 'Singles', 'Individual collectible trading cards, singles, and graded slabs')
ON CONFLICT DO NOTHING;

INSERT INTO categories (id, name, description)
VALUES (2, 'Sealed', 'Factory sealed booster boxes, packs, and bundles')
ON CONFLICT DO NOTHING;

-- Explicit ids above do not advance the identity sequence; move it past the seeded ids and any existing rows
SELECT setval(pg_get_serial_sequence('categories', 'id'), GREATEST((SELECT COALESCE(MAX(id), 0) FROM categories), 2));

-- Trade Assistant: Buy Rules (Cash Payouts)
INSERT INTO buy_rules (priority, category_code, display_name, rate, active)
VALUES
    (1, 'PSA10_BGS_BLACK_LABEL', 'PSA 10 or BGS Black Label', 0.8200, true),
    (2, 'SEALED', 'Sealed product', 0.7000, true),
    (3, 'RAW_NEAR_MINT', 'Near-mint raw single', 0.7700, true),
    (4, 'DEFAULT', 'Everything else', 0.7500, true)
ON CONFLICT DO NOTHING;

-- Trade Assistant: Configurable Trade Parameters
INSERT INTO trade_parameters (param_key, param_value, description)
VALUES
    ('VARIABLE_RESALE_FEE_FRACTION', 0.1200, 'Variable resale cost, platform and payment fees fraction (f)'),
    ('FIXED_HANDLING_FEE_PER_CARD', 0.5000, 'Fixed handling cost per incoming card in CAD (F)'),
    ('TARGET_PROFIT_MARGIN', 0.0800, 'Target profit margin on store cards given (g)'),
    ('DEFAULT_COST_BASIS_RATIO', 0.7700, 'Fallback cost basis to list price ratio for store cards (c)'),
    ('HARD_CAP_RATE', 0.9000, 'Hard ceiling on trade credit rate (cap)'),
    ('COUNTER_FLOOR_RATE', 0.5500, 'Minimum allowable rate to issue counter offer with cash top-up'),
    ('COUNTER_MAX_TOPUP_RATIO', 0.2500, 'Maximum cash top-up allowed as fraction of store list price'),
    ('OPENING_OFFER_DISCOUNT', 0.0300, 'Discount applied to r_max for opening customer offers'),
    ('CONSOLIDATION_THRESHOLD_COUNT', 3.0000, 'Minimum card count to trigger consolidation review'),
    ('CONSOLIDATION_MIN_LARGEST_RATIO', 0.2500, 'Minimum largest card value ratio to target; below this declines'),
    ('CONSOLIDATION_PENALTY_THRESHOLD', 0.5000, 'Threshold below which consolidation penalty applies'),
    ('CONSOLIDATION_PENALTY', 0.0500, 'Rate penalty subtracted from r_max for 25%-50% consolidation'),
    ('MAX_CUSTOMER_CARDS_THRESHOLD', 8.0000, 'Maximum cards before trade requires in-person / manual review'),
    ('DEFAULT_LIQUIDITY_HAIRCUT_HIGH', 0.0000, 'Liquidity haircut for high-velocity cards'),
    ('DEFAULT_LIQUIDITY_HAIRCUT_MEDIUM', 0.0300, 'Liquidity haircut for medium-velocity cards'),
    ('DEFAULT_LIQUIDITY_HAIRCUT_LOW', 0.0800, 'Liquidity haircut for low-velocity / niche cards')
ON CONFLICT DO NOTHING;

-- Trade Assistant: Sample Liquidity Tags
INSERT INTO card_liquidity (pokemontcg_id, liquidity_tier, haircut, notes)
VALUES
    ('base1-4', 'HIGH', 0.0000, 'Base Set Charizard Holo - Premier Grail'),
    ('base1-2', 'HIGH', 0.0000, 'Base Set Blastoise Holo'),
    ('base1-15', 'HIGH', 0.0000, 'Base Set Venusaur Holo'),
    ('sm35-78', 'HIGH', 0.0000, 'Mewtwo GX Secret Rare Shining Legends'),
    ('swsh7-215', 'HIGH', 0.0000, 'Umbreon VMAX Alt Art Evolving Skies')
ON CONFLICT DO NOTHING;

-- Trade Assistant: Sample Manual Price Overrides (Graded slabs & sealed)
INSERT INTO manual_price_overrides (card_id, condition_or_grade, override_price_cad, notes, updated_at)
VALUES
    ('base1-4', 'PSA 10', 4500.00, 'Charizard Base Set Holo PSA 10 gem mint baseline', CURRENT_TIMESTAMP),
    ('base1-4', 'BGS BL', 12000.00, 'Charizard Base Set Holo BGS Black Label 10 pristine', CURRENT_TIMESTAMP),
    ('swsh7-215', 'PSA 10', 1350.00, 'Umbreon VMAX Alt Art Evolving Skies PSA 10', CURRENT_TIMESTAMP),
    ('sv3pt5-151', 'SEALED', 180.00, 'Pokemon 151 Booster Bundle factory sealed box', CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
