-- V3__buylist_chat.sql
-- AI chatbot buylist intake: email OTP sessions, server-side drafts, resolved line items,
-- chat transcripts, LLM spend tracking, and chatbot columns on the existing buylist queue.
-- Idempotent (IF NOT EXISTS) because production was baselined at version 1.

-- Existing admin queue: chatbot submissions land in buylist_submissions
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS source VARCHAR(20);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS currency VARCHAR(3);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS total_market_usd NUMERIC(12, 2);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS eligible_market_usd NUMERIC(12, 2);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS likelihood_pct INTEGER;
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS likelihood_reasons TEXT;
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS red_flags TEXT;
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS owner_decision VARCHAR(20);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS owner_decided_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS counter_amount_usd NUMERIC(12, 2);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS local_date DATE;
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS limit_reset_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS content_hash VARCHAR(64);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS submitter_ip VARCHAR(64);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS draft_id VARCHAR(36);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS chat_transcript TEXT;
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS quote_expires_at TIMESTAMP WITH TIME ZONE;

-- One confirmed chatbot submission per email per America/Toronto day. Manual submissions and
-- admin-reset rows have local_date NULL, which unique indexes ignore (PostgreSQL and H2).
CREATE UNIQUE INDEX IF NOT EXISTS uk_buylist_email_local_date ON buylist_submissions (customer_email, local_date);
CREATE INDEX IF NOT EXISTS idx_buylist_ip_local_date ON buylist_submissions (submitter_ip, local_date);

CREATE TABLE IF NOT EXISTS buylist_otp_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    request_ip VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_buylist_otp_email_created ON buylist_otp_codes (email, created_at);

CREATE TABLE IF NOT EXISTS buylist_chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL,
    created_ip VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS buylist_drafts (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    status VARCHAR(20) NOT NULL,
    notes TEXT,
    submission_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_buylist_drafts_email_status ON buylist_drafts (email, status);

CREATE TABLE IF NOT EXISTS buylist_draft_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id VARCHAR(36) NOT NULL,
    line_no INTEGER NOT NULL,
    kind VARCHAR(10) NOT NULL,
    input_text VARCHAR(500),
    name VARCHAR(200) NOT NULL,
    set_name VARCHAR(150),
    card_number VARCHAR(40),
    variant VARCHAR(40),
    item_condition VARCHAR(30),
    quantity INTEGER NOT NULL,
    card_id VARCHAR(60),
    matched_name VARCHAR(200),
    matched_set VARCHAR(150),
    matched_number VARCHAR(40),
    rarity VARCHAR(80),
    category VARCHAR(40),
    image_url VARCHAR(500),
    unit_market_usd NUMERIC(12, 2),
    eur_trend NUMERIC(12, 2),
    price_updated_at VARCHAR(40),
    price_source VARCHAR(40),
    id_confidence NUMERIC(4, 3),
    resolve_state VARCHAR(20) NOT NULL,
    candidates_json TEXT,
    photo_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_buylist_draft_lines_draft FOREIGN KEY (draft_id) REFERENCES buylist_drafts (id)
);
CREATE INDEX IF NOT EXISTS idx_buylist_draft_lines_draft ON buylist_draft_lines (draft_id, line_no);

CREATE TABLE IF NOT EXISTS buylist_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id VARCHAR(36) NOT NULL,
    sender_role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_buylist_chat_messages_draft FOREIGN KEY (draft_id) REFERENCES buylist_drafts (id)
);
CREATE INDEX IF NOT EXISTS idx_buylist_chat_messages_draft ON buylist_chat_messages (draft_id, created_at);

CREATE TABLE IF NOT EXISTS buylist_submission_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    line_no INTEGER NOT NULL,
    kind VARCHAR(10) NOT NULL,
    name VARCHAR(200) NOT NULL,
    set_name VARCHAR(150),
    card_number VARCHAR(40),
    variant VARCHAR(40),
    item_condition VARCHAR(30),
    quantity INTEGER NOT NULL,
    card_id VARCHAR(60),
    matched_name VARCHAR(200),
    matched_set VARCHAR(150),
    rarity VARCHAR(80),
    image_url VARCHAR(500),
    currency VARCHAR(3) NOT NULL,
    unit_market_usd NUMERIC(12, 2),
    line_market_usd NUMERIC(14, 2),
    eur_trend NUMERIC(12, 2),
    price_updated_at VARCHAR(40),
    id_confidence NUMERIC(4, 3),
    status VARCHAR(20) NOT NULL,
    status_reason VARCHAR(200),
    photo_url VARCHAR(500),
    CONSTRAINT fk_buylist_submission_lines_submission FOREIGN KEY (submission_id) REFERENCES buylist_submissions (id)
);
CREATE INDEX IF NOT EXISTS idx_buylist_submission_lines_submission ON buylist_submission_lines (submission_id, line_no);

CREATE TABLE IF NOT EXISTS buylist_llm_spend (
    spend_date DATE PRIMARY KEY,
    cost_usd NUMERIC(12, 6) NOT NULL,
    calls INTEGER NOT NULL
);
