-- V5__buylist_deals.sql
-- Buylist chat deals: sell / trade / partial, asking prices, shop cards picked for trade, graded price basis.
-- Idempotent (IF NOT EXISTS / ON CONFLICT) because production was baselined at version 1.

ALTER TABLE buylist_drafts ADD COLUMN IF NOT EXISTS deal_type VARCHAR(10);
ALTER TABLE buylist_drafts ADD COLUMN IF NOT EXISTS requested_cash_usd NUMERIC(12, 2);

ALTER TABLE buylist_draft_lines ADD COLUMN IF NOT EXISTS requested_unit_usd NUMERIC(12, 2);
ALTER TABLE buylist_draft_lines ADD COLUMN IF NOT EXISTS price_basis VARCHAR(10);

CREATE TABLE IF NOT EXISTS buylist_draft_trade_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id VARCHAR(36) NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_buylist_draft_trade_item UNIQUE (draft_id, product_id),
    CONSTRAINT fk_buylist_draft_trade_items_draft FOREIGN KEY (draft_id) REFERENCES buylist_drafts (id)
);

ALTER TABLE buylist_submission_lines ADD COLUMN IF NOT EXISTS requested_unit_usd NUMERIC(12, 2);
ALTER TABLE buylist_submission_lines ADD COLUMN IF NOT EXISTS price_basis VARCHAR(10);

ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS deal_type VARCHAR(10);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS requested_cash_usd NUMERIC(12, 2);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS store_cards_json TEXT;
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS store_total_usd NUMERIC(12, 2);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS cash_offer_usd NUMERIC(12, 2);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS trade_credit_usd NUMERIC(12, 2);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS ask_ratio NUMERIC(8, 3);
ALTER TABLE buylist_submissions ADD COLUMN IF NOT EXISTS usd_cad_rate NUMERIC(10, 4);

-- Store-credit rate for buylist trades (cash rates come from buy_rules); editable in admin
INSERT INTO trade_parameters (param_key, param_value, description)
VALUES ('BUYLIST_TRADE_CREDIT_RATE', 0.8000, 'Buylist chat: store credit paid as a fraction of market value')
ON CONFLICT DO NOTHING;
